name: Mark time
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: audible_periodic_increment
          type: number
          label: Seconds between audible notifications of periodic cycle. Somewhat like a metronome.
          value: 0
          placeholder: 0 to deactivate, 600 for every 10 minutes
        - name: display_time
          type: checkbox
          label: Visually display stopwatch time
          value: "false"
    - name: Persistence
      fields:
        - type: label
          label: These are not really settings per se. Persistent storage or "memory" for Mycroft to remember time state.
        - name: tzero
          type: number
          label: "Time-Zero for most recent beginning of mark-time"
          value: 0
          placeholder: 12345678 (in UNIX-time, which is seconds since the Epoch)
        - name: prior_duration 
          type: number
          label: "Prior result duration in seconds"
          value: 0
          placeholder: 60
